server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ********************************
    username: root
    password: wryte

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.surveysystemtext.entity
  global-config:
    db-config:
      id-type: auto
